### ISSUE TITLE
Blog / Post directories

### ISSUE THREAD

**Issue by keithmifsud** [learnk8s/learnk8s.io#17]
@danielepolencic I think you have made a change instead of the normal Jekyll posts, it seems that you're placing posts inside of a dir named _blog. Why? This is not the Jekyll way! But it's fine, I got it working :)

__Sorry about the above, Git could not get the latest changes because of the missing "blog" branch, but now it's fine"__

Also, if possible it will be a lot better if you work on a personal fork instead of directly in the shared repo because these are breaking changes and it takes a while to reverse engineer them without any info from you.

I did so. I forked the learnk8s.io repo and will only merge upstream once. My fork is: https://github.com/keithmifsud/learnk8s.io  if you have a look at the [blog](https://github.com/keithmifsud/learnk8s.io/tree/blog) branch you should notice that I added an author blurb "include". Once I am done, I will submit a PR from my fork:blog to main_repo:master for your review.

I also added instructions on using the author's blurb in the readme file.

**Comment by danielepolencic** [comment]
>This is not the Jekyll way!:tm:

You're right. The blog doesn't follow the Jekyll convention anymore.

I wish Jekyll could place assets next to its blog posts. Unfortunately, this is not possible with `_posts` since those are _legacy_ and _special_ collections.

I documented the change in the readme, and it should be straightforward to add more blog posts now. Also, you can store any PDF, image, SVG, etc. alongside your post. You should have a look at the only post in the blog folder.

The code was changed gradually through a series of PRs. I didn't want to disturb, so I checked and merged myself. Perhaps I could add you as a reviewer next time, so there won't be surprises.

**Comment by keithmifsud** [comment]
@danielepolencic It's fine now. My issue was that the blog branch was deleted and I think it was not fully merged so I couldn't sync the updates. I moved my changes outside of the repo (so I didn't lose them), then pulled and then moved on as normal.

I created an author_blurb include file for you. It's not yet merged to your repo but on my fork:blog you can see what I've done.

**Comment by danielepolencic** [comment]
I think you should raise a PR so we can merge this small change first.

**Comment by keithmifsud** [comment]
@danielepolencic #18

**Comment by danielepolencic** [comment]
I think this can be closed now?

**Comment by keithmifsud** [comment]
I'm closing it as resolve by PR #20
